#include "eclair-html/errors.h"

namespace eclair_html {
namespace html_parser {

const std::vector<std::string> Error::_NAMES = {
    "Abrupt closing of empty comment",
    "Abrupt doctype public identifier",
    "Abrupt doctype system identifier",
    "Absence of digits in numeric character reference",
    "Cdata in html content",
    "Character reference outside unicode range",
    "Control character in input stream",
    "Control character reference",
    "End tag with attributes",
    "Duplicate attribute",
    "End tag with trailing solidus",
    "Eof before tag name",
    "Eof in cdata",
    "Eof in comment",
    "Eof in doctype",
    "Eof in script html comment like text",
    "Eof in tag",
    "Incorrectly closed comment",
    "Incorrectly opened comment",
    "Invalid character sequence after doctype name",
    "Invalid first character of tag name",
    "Missing attribute value",
    "Missing doctype name",
    "Missing doctype public identifier",
    "Missing doctype system identifier",
    "Missing end tag name",
    "Missing quote before doctype public identifier",
    "Missing quote before doctype system identifier",
    "Missing semicolon after character reference",
    "Missing whitespace after doctype public keyword",
    "Missing whitespace after doctype system keyword",
    "Missing whitespace before doctype name",
    "Missing whitespace between attributes",
    "Missing whitespace between doctype public and system identifiers",
    "Nested comment",
    "Noncharacter character reference",
    "Noncharacter in input stream",
    "Non void html element start tag with trailing solidus",
    "Null character reference",
    "Surrogate character reference",
    "Surrogate in input stream",
    "Unexpected character after doctype system identifier",
    "Unexpected character in attribute name",
    "Unexpected character in unquoted attribute value",
    "Unexpected equals sign before attribute name",
    "Unexpected null character",
    "Unexpected question mark instead of tag name",
    "Unexpected solidus in tag",
    "Unknown named character reference",
    "Unexpected tag",
    "Unexpected text",
};

}
} // namespace eclair_html
